name: Build and Push

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "Dockerfile"
      - ".github/workflows/build-image.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/mcprun-playground:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Publish all the servlets
        env:
          XTP_TOKEN: ${{ secrets.XTP_TOKEN }}
        run: echo "Add your publish command here"